name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller pyinstaller.spec

    - name: Verify executable
      run: |
        if [ ! -f "dist/readerspeeder.exe" ]; then
          echo "Executable not found!"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: readerspeeder-executable-windows
        path: dist/readerspeeder.exe  # Ensure the path matches the target name

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Download the compiled application for Windows from the assets below. If you prefer to run from source, follow the instructions in the README.

          **Changes in this release:**
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Set upload URL
      run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Upload Windows Release Asset to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: dist/readerspeeder.exe  # Ensure the path matches the target name
        asset_name: readerspeeder-windows.exe
        asset_content_type: application/octet-stream