name: TestBuild

on:
  push:
    tags:
      - 'TestBuild'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller readerspeeder_debug.spec  # Use the debug spec file

    - name: Zip the build directory
      run: powershell Compress-Archive -Path dist/ReaderSpeeder -DestinationPath dist/ReaderSpeeder.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/ReaderSpeeder.zip